name: Blank Workflow
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run a one-line scriptHello, world test !
        run: echo "Hello, world!"

  test1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test after build
        run: echo "after build"
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: test in parallel with build
        run: echo "parallel with build"