name: Blank Workflow
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run a one-line scriptHello, world test !
        run: echo "Hello, world!"
